version: '3.3'
services:
  db:
    image: mysql
    container_name: mysql-cont
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb' 
      MYSQL_USER: 'user' 
      MYSQL_PASSWORD: '1234' 
      MYSQL_ROOT_PASSWORD: 'r1234'
    ports: 
      - '3307:3306'
    expose: 
      - '3307' 
    volumes:
      - mysqldocker:/var/lib/mysql
    networks:
      - napptilusnet 
  redis:
    image: "redis:alpine"
    container_name: redis-cache  
    ports: 
      - '6379:6379'
    networks:
      - napptilusnet     
volumes:
  mysqldocker:

networks:
  napptilusnet: 
    driver: bridge
    name: napptilusnet